package com.jrsportsgame.jrbm.mapper;

import com.jrsportsgame.jrbm.model.Basicplayer;
import com.jrsportsgame.jrbm.model.BasicplayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicplayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    long countByExample(BasicplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int deleteByExample(BasicplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer bpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int insert(Basicplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int insertSelective(Basicplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    List<Basicplayer> selectByExample(BasicplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    Basicplayer selectByPrimaryKey(Integer bpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Basicplayer record, @Param("example") BasicplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Basicplayer record, @Param("example") BasicplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Basicplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    int updateByPrimaryKey(Basicplayer record);
}