package com.jrsportsgame.jrbm.mapper;

import com.jrsportsgame.jrbm.model.Freemarket;
import com.jrsportsgame.jrbm.model.FreemarketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreemarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    long countByExample(FreemarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int deleteByExample(FreemarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer fpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int insert(Freemarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int insertSelective(Freemarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    List<Freemarket> selectByExample(FreemarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    Freemarket selectByPrimaryKey(Integer fpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Freemarket record, @Param("example") FreemarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Freemarket record, @Param("example") FreemarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Freemarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    int updateByPrimaryKey(Freemarket record);
}