package com.jrsportsgame.jrbm.mapper;

import com.jrsportsgame.jrbm.model.Teamplayer;
import com.jrsportsgame.jrbm.model.TeamplayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamplayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    long countByExample(TeamplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int deleteByExample(TeamplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int insert(Teamplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int insertSelective(Teamplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    List<Teamplayer> selectByExample(TeamplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    Teamplayer selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Teamplayer record, @Param("example") TeamplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Teamplayer record, @Param("example") TeamplayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Teamplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByPrimaryKey(Teamplayer record);
}