package com.jrsportsgame.jrbm.mapper;

import com.jrsportsgame.jrbm.model.Teaminfo;
import com.jrsportsgame.jrbm.model.TeaminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeaminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    long countByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int deleteByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int insert(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int insertSelective(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    List<Teaminfo> selectByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    Teaminfo selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Teaminfo record, @Param("example") TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Teaminfo record, @Param("example") TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    int updateByPrimaryKey(Teaminfo record);
}