package com.jrsportsgame.jrbm.mapper;

import com.jrsportsgame.jrbm.model.UserAuthorize;
import com.jrsportsgame.jrbm.model.UserAuthorizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthorizeMapper {

    long countByExample(UserAuthorizeExample example);


    int deleteByExample(UserAuthorizeExample example);


    int deleteByPrimaryKey(Integer uaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int insert(UserAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int insertSelective(UserAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    List<UserAuthorize> selectByExample(UserAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    UserAuthorize selectByPrimaryKey(Integer uaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") UserAuthorize record, @Param("example") UserAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int updateByExample(@Param("record") UserAuthorize record, @Param("example") UserAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(UserAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    int updateByPrimaryKey(UserAuthorize record);
}