package com.jrsportsgame.jrbm.model;

import java.util.ArrayList;
import java.util.List;

public class BasicplayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public BasicplayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBpidIsNull() {
            addCriterion("bpid is null");
            return (Criteria) this;
        }

        public Criteria andBpidIsNotNull() {
            addCriterion("bpid is not null");
            return (Criteria) this;
        }

        public Criteria andBpidEqualTo(Integer value) {
            addCriterion("bpid =", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidNotEqualTo(Integer value) {
            addCriterion("bpid <>", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidGreaterThan(Integer value) {
            addCriterion("bpid >", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bpid >=", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidLessThan(Integer value) {
            addCriterion("bpid <", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidLessThanOrEqualTo(Integer value) {
            addCriterion("bpid <=", value, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidIn(List<Integer> values) {
            addCriterion("bpid in", values, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidNotIn(List<Integer> values) {
            addCriterion("bpid not in", values, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidBetween(Integer value1, Integer value2) {
            addCriterion("bpid between", value1, value2, "bpid");
            return (Criteria) this;
        }

        public Criteria andBpidNotBetween(Integer value1, Integer value2) {
            addCriterion("bpid not between", value1, value2, "bpid");
            return (Criteria) this;
        }

        public Criteria andEnnameIsNull() {
            addCriterion("enname is null");
            return (Criteria) this;
        }

        public Criteria andEnnameIsNotNull() {
            addCriterion("enname is not null");
            return (Criteria) this;
        }

        public Criteria andEnnameEqualTo(String value) {
            addCriterion("enname =", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotEqualTo(String value) {
            addCriterion("enname <>", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameGreaterThan(String value) {
            addCriterion("enname >", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameGreaterThanOrEqualTo(String value) {
            addCriterion("enname >=", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLessThan(String value) {
            addCriterion("enname <", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLessThanOrEqualTo(String value) {
            addCriterion("enname <=", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLike(String value) {
            addCriterion("enname like", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotLike(String value) {
            addCriterion("enname not like", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameIn(List<String> values) {
            addCriterion("enname in", values, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotIn(List<String> values) {
            addCriterion("enname not in", values, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameBetween(String value1, String value2) {
            addCriterion("enname between", value1, value2, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotBetween(String value1, String value2) {
            addCriterion("enname not between", value1, value2, "enname");
            return (Criteria) this;
        }

        public Criteria andChnameIsNull() {
            addCriterion("chname is null");
            return (Criteria) this;
        }

        public Criteria andChnameIsNotNull() {
            addCriterion("chname is not null");
            return (Criteria) this;
        }

        public Criteria andChnameEqualTo(String value) {
            addCriterion("chname =", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotEqualTo(String value) {
            addCriterion("chname <>", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameGreaterThan(String value) {
            addCriterion("chname >", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameGreaterThanOrEqualTo(String value) {
            addCriterion("chname >=", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLessThan(String value) {
            addCriterion("chname <", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLessThanOrEqualTo(String value) {
            addCriterion("chname <=", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLike(String value) {
            addCriterion("chname like", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotLike(String value) {
            addCriterion("chname not like", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameIn(List<String> values) {
            addCriterion("chname in", values, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotIn(List<String> values) {
            addCriterion("chname not in", values, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameBetween(String value1, String value2) {
            addCriterion("chname between", value1, value2, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotBetween(String value1, String value2) {
            addCriterion("chname not between", value1, value2, "chname");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andOffensiveIsNull() {
            addCriterion("offensive is null");
            return (Criteria) this;
        }

        public Criteria andOffensiveIsNotNull() {
            addCriterion("offensive is not null");
            return (Criteria) this;
        }

        public Criteria andOffensiveEqualTo(Integer value) {
            addCriterion("offensive =", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveNotEqualTo(Integer value) {
            addCriterion("offensive <>", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveGreaterThan(Integer value) {
            addCriterion("offensive >", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("offensive >=", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveLessThan(Integer value) {
            addCriterion("offensive <", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveLessThanOrEqualTo(Integer value) {
            addCriterion("offensive <=", value, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveIn(List<Integer> values) {
            addCriterion("offensive in", values, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveNotIn(List<Integer> values) {
            addCriterion("offensive not in", values, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveBetween(Integer value1, Integer value2) {
            addCriterion("offensive between", value1, value2, "offensive");
            return (Criteria) this;
        }

        public Criteria andOffensiveNotBetween(Integer value1, Integer value2) {
            addCriterion("offensive not between", value1, value2, "offensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveIsNull() {
            addCriterion("defensive is null");
            return (Criteria) this;
        }

        public Criteria andDefensiveIsNotNull() {
            addCriterion("defensive is not null");
            return (Criteria) this;
        }

        public Criteria andDefensiveEqualTo(Integer value) {
            addCriterion("defensive =", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveNotEqualTo(Integer value) {
            addCriterion("defensive <>", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveGreaterThan(Integer value) {
            addCriterion("defensive >", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("defensive >=", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveLessThan(Integer value) {
            addCriterion("defensive <", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveLessThanOrEqualTo(Integer value) {
            addCriterion("defensive <=", value, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveIn(List<Integer> values) {
            addCriterion("defensive in", values, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveNotIn(List<Integer> values) {
            addCriterion("defensive not in", values, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveBetween(Integer value1, Integer value2) {
            addCriterion("defensive between", value1, value2, "defensive");
            return (Criteria) this;
        }

        public Criteria andDefensiveNotBetween(Integer value1, Integer value2) {
            addCriterion("defensive not between", value1, value2, "defensive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basicplayer
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basicplayer
     *
     * @mbg.generated Sun Jun 23 20:20:03 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}