package com.jrsportsgame.jrbm.model;

public class Basicplayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicplayer.bpid
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    private Integer bpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicplayer.enname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    private String enname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicplayer.chname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    private String chname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicplayer.offensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    private Integer offensive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicplayer.defensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    private Integer defensive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicplayer.bpid
     *
     * @return the value of basicplayer.bpid
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public Integer getBpid() {
        return bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicplayer.bpid
     *
     * @param bpid the value for basicplayer.bpid
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public void setBpid(Integer bpid) {
        this.bpid = bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicplayer.enname
     *
     * @return the value of basicplayer.enname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicplayer.enname
     *
     * @param enname the value for basicplayer.enname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicplayer.chname
     *
     * @return the value of basicplayer.chname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public String getChname() {
        return chname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicplayer.chname
     *
     * @param chname the value for basicplayer.chname
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public void setChname(String chname) {
        this.chname = chname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicplayer.offensive
     *
     * @return the value of basicplayer.offensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public Integer getOffensive() {
        return offensive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicplayer.offensive
     *
     * @param offensive the value for basicplayer.offensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public void setOffensive(Integer offensive) {
        this.offensive = offensive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicplayer.defensive
     *
     * @return the value of basicplayer.defensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public Integer getDefensive() {
        return defensive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicplayer.defensive
     *
     * @param defensive the value for basicplayer.defensive
     *
     * @mbg.generated Wed Jun 19 22:23:49 GMT+08:00 2019
     */
    public void setDefensive(Integer defensive) {
        this.defensive = defensive;
    }
}