package com.jrsportsgame.jrbm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FreemarketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public FreemarketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFpidIsNull() {
            addCriterion("fpid is null");
            return (Criteria) this;
        }

        public Criteria andFpidIsNotNull() {
            addCriterion("fpid is not null");
            return (Criteria) this;
        }

        public Criteria andFpidEqualTo(Integer value) {
            addCriterion("fpid =", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotEqualTo(Integer value) {
            addCriterion("fpid <>", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidGreaterThan(Integer value) {
            addCriterion("fpid >", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fpid >=", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidLessThan(Integer value) {
            addCriterion("fpid <", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidLessThanOrEqualTo(Integer value) {
            addCriterion("fpid <=", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidIn(List<Integer> values) {
            addCriterion("fpid in", values, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotIn(List<Integer> values) {
            addCriterion("fpid not in", values, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidBetween(Integer value1, Integer value2) {
            addCriterion("fpid between", value1, value2, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotBetween(Integer value1, Integer value2) {
            addCriterion("fpid not between", value1, value2, "fpid");
            return (Criteria) this;
        }

        public Criteria andUpidIsNull() {
            addCriterion("upid is null");
            return (Criteria) this;
        }

        public Criteria andUpidIsNotNull() {
            addCriterion("upid is not null");
            return (Criteria) this;
        }

        public Criteria andUpidEqualTo(Integer value) {
            addCriterion("upid =", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotEqualTo(Integer value) {
            addCriterion("upid <>", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidGreaterThan(Integer value) {
            addCriterion("upid >", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("upid >=", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidLessThan(Integer value) {
            addCriterion("upid <", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidLessThanOrEqualTo(Integer value) {
            addCriterion("upid <=", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidIn(List<Integer> values) {
            addCriterion("upid in", values, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotIn(List<Integer> values) {
            addCriterion("upid not in", values, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidBetween(Integer value1, Integer value2) {
            addCriterion("upid between", value1, value2, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotBetween(Integer value1, Integer value2) {
            addCriterion("upid not between", value1, value2, "upid");
            return (Criteria) this;
        }

        public Criteria andFreetimeIsNull() {
            addCriterion("freetime is null");
            return (Criteria) this;
        }

        public Criteria andFreetimeIsNotNull() {
            addCriterion("freetime is not null");
            return (Criteria) this;
        }

        public Criteria andFreetimeEqualTo(Date value) {
            addCriterion("freetime =", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotEqualTo(Date value) {
            addCriterion("freetime <>", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeGreaterThan(Date value) {
            addCriterion("freetime >", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("freetime >=", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeLessThan(Date value) {
            addCriterion("freetime <", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeLessThanOrEqualTo(Date value) {
            addCriterion("freetime <=", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeIn(List<Date> values) {
            addCriterion("freetime in", values, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotIn(List<Date> values) {
            addCriterion("freetime not in", values, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeBetween(Date value1, Date value2) {
            addCriterion("freetime between", value1, value2, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotBetween(Date value1, Date value2) {
            addCriterion("freetime not between", value1, value2, "freetime");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Integer value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Integer value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Integer value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Integer value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Integer value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Integer> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Integer> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Integer value1, Integer value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freemarket
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table freemarket
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}