package com.jrsportsgame.jrbm.model;

import java.util.Date;

public class Freemarket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freemarket.fpid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    private Integer fpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freemarket.upid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    private Integer upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freemarket.freetime
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    private Date freetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freemarket.source
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    private Integer source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freemarket.status
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freemarket.fpid
     *
     * @return the value of freemarket.fpid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Integer getFpid() {
        return fpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freemarket.fpid
     *
     * @param fpid the value for freemarket.fpid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setFpid(Integer fpid) {
        this.fpid = fpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freemarket.upid
     *
     * @return the value of freemarket.upid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Integer getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freemarket.upid
     *
     * @param upid the value for freemarket.upid
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setUpid(Integer upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freemarket.freetime
     *
     * @return the value of freemarket.freetime
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Date getFreetime() {
        return freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freemarket.freetime
     *
     * @param freetime the value for freemarket.freetime
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setFreetime(Date freetime) {
        this.freetime = freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freemarket.source
     *
     * @return the value of freemarket.source
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freemarket.source
     *
     * @param source the value for freemarket.source
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freemarket.status
     *
     * @return the value of freemarket.status
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freemarket.status
     *
     * @param status the value for freemarket.status
     *
     * @mbg.generated Sun Jun 23 12:47:16 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}