package com.jrsportsgame.jrbm.model;

public class Teamplayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.starting1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer starting1upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.starting2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer starting2upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.starting3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer starting3upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.starting4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer starting4upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.starting5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer starting5upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub1upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub2upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub3upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub4upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub5upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub6upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub6upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.sub7upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sub7upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.unreg1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer unreg1upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.unreg2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer unreg2upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamplayer.unreg3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer unreg3upid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.tid
     *
     * @return the value of teamplayer.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.tid
     *
     * @param tid the value for teamplayer.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.starting1upid
     *
     * @return the value of teamplayer.starting1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getStarting1upid() {
        return starting1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.starting1upid
     *
     * @param starting1upid the value for teamplayer.starting1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setStarting1upid(Integer starting1upid) {
        this.starting1upid = starting1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.starting2upid
     *
     * @return the value of teamplayer.starting2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getStarting2upid() {
        return starting2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.starting2upid
     *
     * @param starting2upid the value for teamplayer.starting2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setStarting2upid(Integer starting2upid) {
        this.starting2upid = starting2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.starting3upid
     *
     * @return the value of teamplayer.starting3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getStarting3upid() {
        return starting3upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.starting3upid
     *
     * @param starting3upid the value for teamplayer.starting3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setStarting3upid(Integer starting3upid) {
        this.starting3upid = starting3upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.starting4upid
     *
     * @return the value of teamplayer.starting4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getStarting4upid() {
        return starting4upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.starting4upid
     *
     * @param starting4upid the value for teamplayer.starting4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setStarting4upid(Integer starting4upid) {
        this.starting4upid = starting4upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.starting5upid
     *
     * @return the value of teamplayer.starting5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getStarting5upid() {
        return starting5upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.starting5upid
     *
     * @param starting5upid the value for teamplayer.starting5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setStarting5upid(Integer starting5upid) {
        this.starting5upid = starting5upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub1upid
     *
     * @return the value of teamplayer.sub1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub1upid() {
        return sub1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub1upid
     *
     * @param sub1upid the value for teamplayer.sub1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub1upid(Integer sub1upid) {
        this.sub1upid = sub1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub2upid
     *
     * @return the value of teamplayer.sub2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub2upid() {
        return sub2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub2upid
     *
     * @param sub2upid the value for teamplayer.sub2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub2upid(Integer sub2upid) {
        this.sub2upid = sub2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub3upid
     *
     * @return the value of teamplayer.sub3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub3upid() {
        return sub3upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub3upid
     *
     * @param sub3upid the value for teamplayer.sub3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub3upid(Integer sub3upid) {
        this.sub3upid = sub3upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub4upid
     *
     * @return the value of teamplayer.sub4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub4upid() {
        return sub4upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub4upid
     *
     * @param sub4upid the value for teamplayer.sub4upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub4upid(Integer sub4upid) {
        this.sub4upid = sub4upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub5upid
     *
     * @return the value of teamplayer.sub5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub5upid() {
        return sub5upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub5upid
     *
     * @param sub5upid the value for teamplayer.sub5upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub5upid(Integer sub5upid) {
        this.sub5upid = sub5upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub6upid
     *
     * @return the value of teamplayer.sub6upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub6upid() {
        return sub6upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub6upid
     *
     * @param sub6upid the value for teamplayer.sub6upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub6upid(Integer sub6upid) {
        this.sub6upid = sub6upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.sub7upid
     *
     * @return the value of teamplayer.sub7upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSub7upid() {
        return sub7upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.sub7upid
     *
     * @param sub7upid the value for teamplayer.sub7upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSub7upid(Integer sub7upid) {
        this.sub7upid = sub7upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.unreg1upid
     *
     * @return the value of teamplayer.unreg1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getUnreg1upid() {
        return unreg1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.unreg1upid
     *
     * @param unreg1upid the value for teamplayer.unreg1upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setUnreg1upid(Integer unreg1upid) {
        this.unreg1upid = unreg1upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.unreg2upid
     *
     * @return the value of teamplayer.unreg2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getUnreg2upid() {
        return unreg2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.unreg2upid
     *
     * @param unreg2upid the value for teamplayer.unreg2upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setUnreg2upid(Integer unreg2upid) {
        this.unreg2upid = unreg2upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamplayer.unreg3upid
     *
     * @return the value of teamplayer.unreg3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getUnreg3upid() {
        return unreg3upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamplayer.unreg3upid
     *
     * @param unreg3upid the value for teamplayer.unreg3upid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setUnreg3upid(Integer unreg3upid) {
        this.unreg3upid = unreg3upid;
    }
}