package com.jrsportsgame.jrbm.model;

import java.util.ArrayList;
import java.util.List;

public class TeamplayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public TeamplayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(Integer value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(Integer value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(Integer value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(Integer value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(Integer value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<Integer> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<Integer> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(Integer value1, Integer value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(Integer value1, Integer value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidIsNull() {
            addCriterion("starting1upid is null");
            return (Criteria) this;
        }

        public Criteria andStarting1upidIsNotNull() {
            addCriterion("starting1upid is not null");
            return (Criteria) this;
        }

        public Criteria andStarting1upidEqualTo(Integer value) {
            addCriterion("starting1upid =", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidNotEqualTo(Integer value) {
            addCriterion("starting1upid <>", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidGreaterThan(Integer value) {
            addCriterion("starting1upid >", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("starting1upid >=", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidLessThan(Integer value) {
            addCriterion("starting1upid <", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidLessThanOrEqualTo(Integer value) {
            addCriterion("starting1upid <=", value, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidIn(List<Integer> values) {
            addCriterion("starting1upid in", values, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidNotIn(List<Integer> values) {
            addCriterion("starting1upid not in", values, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidBetween(Integer value1, Integer value2) {
            addCriterion("starting1upid between", value1, value2, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting1upidNotBetween(Integer value1, Integer value2) {
            addCriterion("starting1upid not between", value1, value2, "starting1upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidIsNull() {
            addCriterion("starting2upid is null");
            return (Criteria) this;
        }

        public Criteria andStarting2upidIsNotNull() {
            addCriterion("starting2upid is not null");
            return (Criteria) this;
        }

        public Criteria andStarting2upidEqualTo(Integer value) {
            addCriterion("starting2upid =", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidNotEqualTo(Integer value) {
            addCriterion("starting2upid <>", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidGreaterThan(Integer value) {
            addCriterion("starting2upid >", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("starting2upid >=", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidLessThan(Integer value) {
            addCriterion("starting2upid <", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidLessThanOrEqualTo(Integer value) {
            addCriterion("starting2upid <=", value, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidIn(List<Integer> values) {
            addCriterion("starting2upid in", values, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidNotIn(List<Integer> values) {
            addCriterion("starting2upid not in", values, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidBetween(Integer value1, Integer value2) {
            addCriterion("starting2upid between", value1, value2, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting2upidNotBetween(Integer value1, Integer value2) {
            addCriterion("starting2upid not between", value1, value2, "starting2upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidIsNull() {
            addCriterion("starting3upid is null");
            return (Criteria) this;
        }

        public Criteria andStarting3upidIsNotNull() {
            addCriterion("starting3upid is not null");
            return (Criteria) this;
        }

        public Criteria andStarting3upidEqualTo(Integer value) {
            addCriterion("starting3upid =", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidNotEqualTo(Integer value) {
            addCriterion("starting3upid <>", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidGreaterThan(Integer value) {
            addCriterion("starting3upid >", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("starting3upid >=", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidLessThan(Integer value) {
            addCriterion("starting3upid <", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidLessThanOrEqualTo(Integer value) {
            addCriterion("starting3upid <=", value, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidIn(List<Integer> values) {
            addCriterion("starting3upid in", values, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidNotIn(List<Integer> values) {
            addCriterion("starting3upid not in", values, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidBetween(Integer value1, Integer value2) {
            addCriterion("starting3upid between", value1, value2, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting3upidNotBetween(Integer value1, Integer value2) {
            addCriterion("starting3upid not between", value1, value2, "starting3upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidIsNull() {
            addCriterion("starting4upid is null");
            return (Criteria) this;
        }

        public Criteria andStarting4upidIsNotNull() {
            addCriterion("starting4upid is not null");
            return (Criteria) this;
        }

        public Criteria andStarting4upidEqualTo(Integer value) {
            addCriterion("starting4upid =", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidNotEqualTo(Integer value) {
            addCriterion("starting4upid <>", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidGreaterThan(Integer value) {
            addCriterion("starting4upid >", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("starting4upid >=", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidLessThan(Integer value) {
            addCriterion("starting4upid <", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidLessThanOrEqualTo(Integer value) {
            addCriterion("starting4upid <=", value, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidIn(List<Integer> values) {
            addCriterion("starting4upid in", values, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidNotIn(List<Integer> values) {
            addCriterion("starting4upid not in", values, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidBetween(Integer value1, Integer value2) {
            addCriterion("starting4upid between", value1, value2, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting4upidNotBetween(Integer value1, Integer value2) {
            addCriterion("starting4upid not between", value1, value2, "starting4upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidIsNull() {
            addCriterion("starting5upid is null");
            return (Criteria) this;
        }

        public Criteria andStarting5upidIsNotNull() {
            addCriterion("starting5upid is not null");
            return (Criteria) this;
        }

        public Criteria andStarting5upidEqualTo(Integer value) {
            addCriterion("starting5upid =", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidNotEqualTo(Integer value) {
            addCriterion("starting5upid <>", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidGreaterThan(Integer value) {
            addCriterion("starting5upid >", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("starting5upid >=", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidLessThan(Integer value) {
            addCriterion("starting5upid <", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidLessThanOrEqualTo(Integer value) {
            addCriterion("starting5upid <=", value, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidIn(List<Integer> values) {
            addCriterion("starting5upid in", values, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidNotIn(List<Integer> values) {
            addCriterion("starting5upid not in", values, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidBetween(Integer value1, Integer value2) {
            addCriterion("starting5upid between", value1, value2, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andStarting5upidNotBetween(Integer value1, Integer value2) {
            addCriterion("starting5upid not between", value1, value2, "starting5upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidIsNull() {
            addCriterion("sub1upid is null");
            return (Criteria) this;
        }

        public Criteria andSub1upidIsNotNull() {
            addCriterion("sub1upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub1upidEqualTo(Integer value) {
            addCriterion("sub1upid =", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidNotEqualTo(Integer value) {
            addCriterion("sub1upid <>", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidGreaterThan(Integer value) {
            addCriterion("sub1upid >", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub1upid >=", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidLessThan(Integer value) {
            addCriterion("sub1upid <", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub1upid <=", value, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidIn(List<Integer> values) {
            addCriterion("sub1upid in", values, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidNotIn(List<Integer> values) {
            addCriterion("sub1upid not in", values, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidBetween(Integer value1, Integer value2) {
            addCriterion("sub1upid between", value1, value2, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub1upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub1upid not between", value1, value2, "sub1upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidIsNull() {
            addCriterion("sub2upid is null");
            return (Criteria) this;
        }

        public Criteria andSub2upidIsNotNull() {
            addCriterion("sub2upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub2upidEqualTo(Integer value) {
            addCriterion("sub2upid =", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidNotEqualTo(Integer value) {
            addCriterion("sub2upid <>", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidGreaterThan(Integer value) {
            addCriterion("sub2upid >", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub2upid >=", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidLessThan(Integer value) {
            addCriterion("sub2upid <", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub2upid <=", value, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidIn(List<Integer> values) {
            addCriterion("sub2upid in", values, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidNotIn(List<Integer> values) {
            addCriterion("sub2upid not in", values, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidBetween(Integer value1, Integer value2) {
            addCriterion("sub2upid between", value1, value2, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub2upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub2upid not between", value1, value2, "sub2upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidIsNull() {
            addCriterion("sub3upid is null");
            return (Criteria) this;
        }

        public Criteria andSub3upidIsNotNull() {
            addCriterion("sub3upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub3upidEqualTo(Integer value) {
            addCriterion("sub3upid =", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidNotEqualTo(Integer value) {
            addCriterion("sub3upid <>", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidGreaterThan(Integer value) {
            addCriterion("sub3upid >", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub3upid >=", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidLessThan(Integer value) {
            addCriterion("sub3upid <", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub3upid <=", value, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidIn(List<Integer> values) {
            addCriterion("sub3upid in", values, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidNotIn(List<Integer> values) {
            addCriterion("sub3upid not in", values, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidBetween(Integer value1, Integer value2) {
            addCriterion("sub3upid between", value1, value2, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub3upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub3upid not between", value1, value2, "sub3upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidIsNull() {
            addCriterion("sub4upid is null");
            return (Criteria) this;
        }

        public Criteria andSub4upidIsNotNull() {
            addCriterion("sub4upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub4upidEqualTo(Integer value) {
            addCriterion("sub4upid =", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidNotEqualTo(Integer value) {
            addCriterion("sub4upid <>", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidGreaterThan(Integer value) {
            addCriterion("sub4upid >", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub4upid >=", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidLessThan(Integer value) {
            addCriterion("sub4upid <", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub4upid <=", value, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidIn(List<Integer> values) {
            addCriterion("sub4upid in", values, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidNotIn(List<Integer> values) {
            addCriterion("sub4upid not in", values, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidBetween(Integer value1, Integer value2) {
            addCriterion("sub4upid between", value1, value2, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub4upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub4upid not between", value1, value2, "sub4upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidIsNull() {
            addCriterion("sub5upid is null");
            return (Criteria) this;
        }

        public Criteria andSub5upidIsNotNull() {
            addCriterion("sub5upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub5upidEqualTo(Integer value) {
            addCriterion("sub5upid =", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidNotEqualTo(Integer value) {
            addCriterion("sub5upid <>", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidGreaterThan(Integer value) {
            addCriterion("sub5upid >", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub5upid >=", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidLessThan(Integer value) {
            addCriterion("sub5upid <", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub5upid <=", value, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidIn(List<Integer> values) {
            addCriterion("sub5upid in", values, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidNotIn(List<Integer> values) {
            addCriterion("sub5upid not in", values, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidBetween(Integer value1, Integer value2) {
            addCriterion("sub5upid between", value1, value2, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub5upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub5upid not between", value1, value2, "sub5upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidIsNull() {
            addCriterion("sub6upid is null");
            return (Criteria) this;
        }

        public Criteria andSub6upidIsNotNull() {
            addCriterion("sub6upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub6upidEqualTo(Integer value) {
            addCriterion("sub6upid =", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidNotEqualTo(Integer value) {
            addCriterion("sub6upid <>", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidGreaterThan(Integer value) {
            addCriterion("sub6upid >", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub6upid >=", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidLessThan(Integer value) {
            addCriterion("sub6upid <", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub6upid <=", value, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidIn(List<Integer> values) {
            addCriterion("sub6upid in", values, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidNotIn(List<Integer> values) {
            addCriterion("sub6upid not in", values, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidBetween(Integer value1, Integer value2) {
            addCriterion("sub6upid between", value1, value2, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub6upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub6upid not between", value1, value2, "sub6upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidIsNull() {
            addCriterion("sub7upid is null");
            return (Criteria) this;
        }

        public Criteria andSub7upidIsNotNull() {
            addCriterion("sub7upid is not null");
            return (Criteria) this;
        }

        public Criteria andSub7upidEqualTo(Integer value) {
            addCriterion("sub7upid =", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidNotEqualTo(Integer value) {
            addCriterion("sub7upid <>", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidGreaterThan(Integer value) {
            addCriterion("sub7upid >", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub7upid >=", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidLessThan(Integer value) {
            addCriterion("sub7upid <", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidLessThanOrEqualTo(Integer value) {
            addCriterion("sub7upid <=", value, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidIn(List<Integer> values) {
            addCriterion("sub7upid in", values, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidNotIn(List<Integer> values) {
            addCriterion("sub7upid not in", values, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidBetween(Integer value1, Integer value2) {
            addCriterion("sub7upid between", value1, value2, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andSub7upidNotBetween(Integer value1, Integer value2) {
            addCriterion("sub7upid not between", value1, value2, "sub7upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidIsNull() {
            addCriterion("unreg1upid is null");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidIsNotNull() {
            addCriterion("unreg1upid is not null");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidEqualTo(Integer value) {
            addCriterion("unreg1upid =", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidNotEqualTo(Integer value) {
            addCriterion("unreg1upid <>", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidGreaterThan(Integer value) {
            addCriterion("unreg1upid >", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unreg1upid >=", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidLessThan(Integer value) {
            addCriterion("unreg1upid <", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidLessThanOrEqualTo(Integer value) {
            addCriterion("unreg1upid <=", value, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidIn(List<Integer> values) {
            addCriterion("unreg1upid in", values, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidNotIn(List<Integer> values) {
            addCriterion("unreg1upid not in", values, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidBetween(Integer value1, Integer value2) {
            addCriterion("unreg1upid between", value1, value2, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg1upidNotBetween(Integer value1, Integer value2) {
            addCriterion("unreg1upid not between", value1, value2, "unreg1upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidIsNull() {
            addCriterion("unreg2upid is null");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidIsNotNull() {
            addCriterion("unreg2upid is not null");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidEqualTo(Integer value) {
            addCriterion("unreg2upid =", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidNotEqualTo(Integer value) {
            addCriterion("unreg2upid <>", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidGreaterThan(Integer value) {
            addCriterion("unreg2upid >", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unreg2upid >=", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidLessThan(Integer value) {
            addCriterion("unreg2upid <", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidLessThanOrEqualTo(Integer value) {
            addCriterion("unreg2upid <=", value, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidIn(List<Integer> values) {
            addCriterion("unreg2upid in", values, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidNotIn(List<Integer> values) {
            addCriterion("unreg2upid not in", values, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidBetween(Integer value1, Integer value2) {
            addCriterion("unreg2upid between", value1, value2, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg2upidNotBetween(Integer value1, Integer value2) {
            addCriterion("unreg2upid not between", value1, value2, "unreg2upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidIsNull() {
            addCriterion("unreg3upid is null");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidIsNotNull() {
            addCriterion("unreg3upid is not null");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidEqualTo(Integer value) {
            addCriterion("unreg3upid =", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidNotEqualTo(Integer value) {
            addCriterion("unreg3upid <>", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidGreaterThan(Integer value) {
            addCriterion("unreg3upid >", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unreg3upid >=", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidLessThan(Integer value) {
            addCriterion("unreg3upid <", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidLessThanOrEqualTo(Integer value) {
            addCriterion("unreg3upid <=", value, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidIn(List<Integer> values) {
            addCriterion("unreg3upid in", values, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidNotIn(List<Integer> values) {
            addCriterion("unreg3upid not in", values, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidBetween(Integer value1, Integer value2) {
            addCriterion("unreg3upid between", value1, value2, "unreg3upid");
            return (Criteria) this;
        }

        public Criteria andUnreg3upidNotBetween(Integer value1, Integer value2) {
            addCriterion("unreg3upid not between", value1, value2, "unreg3upid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teamplayer
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teamplayer
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}