package com.jrsportsgame.jrbm.model;

public class Teaminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.uid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.sid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tname
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.jrcoin
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer jrcoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.jrdiamond
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer jrdiamond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.exp
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    private Integer exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tid
     *
     * @return the value of teaminfo.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tid
     *
     * @param tid the value for teaminfo.tid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.uid
     *
     * @return the value of teaminfo.uid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.uid
     *
     * @param uid the value for teaminfo.uid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.sid
     *
     * @return the value of teaminfo.sid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.sid
     *
     * @param sid the value for teaminfo.sid
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tname
     *
     * @return the value of teaminfo.tname
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tname
     *
     * @param tname the value for teaminfo.tname
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.jrcoin
     *
     * @return the value of teaminfo.jrcoin
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getJrcoin() {
        return jrcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.jrcoin
     *
     * @param jrcoin the value for teaminfo.jrcoin
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setJrcoin(Integer jrcoin) {
        this.jrcoin = jrcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.jrdiamond
     *
     * @return the value of teaminfo.jrdiamond
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getJrdiamond() {
        return jrdiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.jrdiamond
     *
     * @param jrdiamond the value for teaminfo.jrdiamond
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setJrdiamond(Integer jrdiamond) {
        this.jrdiamond = jrdiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.exp
     *
     * @return the value of teaminfo.exp
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.exp
     *
     * @param exp the value for teaminfo.exp
     *
     * @mbg.generated Tue Jun 18 21:30:59 GMT+08:00 2019
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }
}