package com.jrsportsgame.jrbm.model;

public class Userplayers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.upid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.bpid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer bpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.tid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.salary
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.status
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.position
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    private Integer position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.upid
     *
     * @return the value of userplayers.upid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.upid
     *
     * @param upid the value for userplayers.upid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setUpid(Integer upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.bpid
     *
     * @return the value of userplayers.bpid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getBpid() {
        return bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.bpid
     *
     * @param bpid the value for userplayers.bpid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setBpid(Integer bpid) {
        this.bpid = bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.tid
     *
     * @return the value of userplayers.tid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.tid
     *
     * @param tid the value for userplayers.tid
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.salary
     *
     * @return the value of userplayers.salary
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.salary
     *
     * @param salary the value for userplayers.salary
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.status
     *
     * @return the value of userplayers.status
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.status
     *
     * @param status the value for userplayers.status
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.position
     *
     * @return the value of userplayers.position
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.position
     *
     * @param position the value for userplayers.position
     *
     * @mbg.generated Mon Jun 24 13:08:53 GMT+08:00 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }
}