package com.jrsportsgame.jrbm.model;

public class Userplayers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.upid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    private Integer upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.bpid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    private Integer bpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userplayers.tid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.upid
     *
     * @return the value of userplayers.upid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public Integer getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.upid
     *
     * @param upid the value for userplayers.upid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public void setUpid(Integer upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.bpid
     *
     * @return the value of userplayers.bpid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public Integer getBpid() {
        return bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.bpid
     *
     * @param bpid the value for userplayers.bpid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public void setBpid(Integer bpid) {
        this.bpid = bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userplayers.tid
     *
     * @return the value of userplayers.tid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userplayers.tid
     *
     * @param tid the value for userplayers.tid
     *
     * @mbg.generated Wed Jun 19 22:09:21 GMT+08:00 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}