package com.jrsportsgame.jrbm.model;

public class UserAuthorize {

    private Integer uaid;


    private Integer uid;


    private Integer authorizeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authorize.authorize_token
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    private String authorizeToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authorize.password
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authorize.uaid
     *
     * @return the value of user_authorize.uaid
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public Integer getUaid() {
        return uaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authorize.uaid
     *
     * @param uaid the value for user_authorize.uaid
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setUaid(Integer uaid) {
        this.uaid = uaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authorize.uid
     *
     * @return the value of user_authorize.uid
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authorize.uid
     *
     * @param uid the value for user_authorize.uid
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authorize.authorize_type
     *
     * @return the value of user_authorize.authorize_type
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public Integer getAuthorizeType() {
        return authorizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authorize.authorize_type
     *
     * @param authorizeType the value for user_authorize.authorize_type
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setAuthorizeType(Integer authorizeType) {
        this.authorizeType = authorizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authorize.authorize_token
     *
     * @return the value of user_authorize.authorize_token
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public String getAuthorizeToken() {
        return authorizeToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authorize.authorize_token
     *
     * @param authorizeToken the value for user_authorize.authorize_token
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setAuthorizeToken(String authorizeToken) {
        this.authorizeToken = authorizeToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authorize.password
     *
     * @return the value of user_authorize.password
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authorize.password
     *
     * @param password the value for user_authorize.password
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}