package com.jrsportsgame.jrbm.model;

import java.util.ArrayList;
import java.util.List;

public class UserAuthorizeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public UserAuthorizeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUaidIsNull() {
            addCriterion("uaid is null");
            return (Criteria) this;
        }

        public Criteria andUaidIsNotNull() {
            addCriterion("uaid is not null");
            return (Criteria) this;
        }

        public Criteria andUaidEqualTo(Integer value) {
            addCriterion("uaid =", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidNotEqualTo(Integer value) {
            addCriterion("uaid <>", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidGreaterThan(Integer value) {
            addCriterion("uaid >", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uaid >=", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidLessThan(Integer value) {
            addCriterion("uaid <", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidLessThanOrEqualTo(Integer value) {
            addCriterion("uaid <=", value, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidIn(List<Integer> values) {
            addCriterion("uaid in", values, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidNotIn(List<Integer> values) {
            addCriterion("uaid not in", values, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidBetween(Integer value1, Integer value2) {
            addCriterion("uaid between", value1, value2, "uaid");
            return (Criteria) this;
        }

        public Criteria andUaidNotBetween(Integer value1, Integer value2) {
            addCriterion("uaid not between", value1, value2, "uaid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeIsNull() {
            addCriterion("authorize_type is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeIsNotNull() {
            addCriterion("authorize_type is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeEqualTo(Integer value) {
            addCriterion("authorize_type =", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeNotEqualTo(Integer value) {
            addCriterion("authorize_type <>", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeGreaterThan(Integer value) {
            addCriterion("authorize_type >", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("authorize_type >=", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeLessThan(Integer value) {
            addCriterion("authorize_type <", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("authorize_type <=", value, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeIn(List<Integer> values) {
            addCriterion("authorize_type in", values, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeNotIn(List<Integer> values) {
            addCriterion("authorize_type not in", values, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeBetween(Integer value1, Integer value2) {
            addCriterion("authorize_type between", value1, value2, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("authorize_type not between", value1, value2, "authorizeType");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenIsNull() {
            addCriterion("authorize_token is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenIsNotNull() {
            addCriterion("authorize_token is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenEqualTo(String value) {
            addCriterion("authorize_token =", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenNotEqualTo(String value) {
            addCriterion("authorize_token <>", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenGreaterThan(String value) {
            addCriterion("authorize_token >", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenGreaterThanOrEqualTo(String value) {
            addCriterion("authorize_token >=", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenLessThan(String value) {
            addCriterion("authorize_token <", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenLessThanOrEqualTo(String value) {
            addCriterion("authorize_token <=", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenLike(String value) {
            addCriterion("authorize_token like", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenNotLike(String value) {
            addCriterion("authorize_token not like", value, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenIn(List<String> values) {
            addCriterion("authorize_token in", values, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenNotIn(List<String> values) {
            addCriterion("authorize_token not in", values, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenBetween(String value1, String value2) {
            addCriterion("authorize_token between", value1, value2, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizeTokenNotBetween(String value1, String value2) {
            addCriterion("authorize_token not between", value1, value2, "authorizeToken");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_authorize
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_authorize
     *
     * @mbg.generated Tue Jun 18 13:29:11 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}